-- Run in Supabase → SQL Editor.
-- If you already created the old JSONB version and do not need its test data,
-- uncomment the next line before running:
-- drop table if exists public.form_submissions;

create table if not exists public.form_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  first_name text not null default '',
  last_name text not null default '',
  email text not null default '',
  company text not null default '',
  job_title text not null default '',
  phone text not null default '',
  interest text not null default '',
  message text not null default ''
);

comment on table public.form_submissions is 'LogiKal demo form submissions with one column per form field';

alter table public.form_submissions enable row level security;

-- No public policies: only server (service role key) inserts/selects via API routes.
notify pgrst, 'reload schema';
